### ISSUE TITLE
ILocatorService.Locate using 'withKey' doesn't work for wrapped types.

### ISSUE THREAD

**Issue by eglauko** [ipjohnson/Grace#185]
I have a class named OptionalWrapperStrategy (for Optional<T>) extending BaseWrapperStrategy, and implementing IMissingExportStrategyProvider, IMissingDependencyExpressionProvider.

I can inject Optional<T> with keys in properties, construtor parameters, and methods parameters.

If i try locate Optional<T> using ILocatorService.Locate works fine, but if i try use 'withKey' an exception is thrown, and the methods of OptionalWrapperStrategy are not called.

**Comment by ipjohnson** [comment]
Could you include your optional wrapper implementation and I can take a look this evening?

**Comment by eglauko** [comment]
[Optional.zip](https://github.com/ipjohnson/Grace/files/2271304/Optional.zip)

**Comment by ipjohnson** [comment]
I've been able to replicate this problem in my environment so I can fix it. The one thing I will say is that this resolution won't be fast. Grace only caches delegates for non keyed exports, which wouldn't be a problem because it would be cached at the export itself but it's a wrapped/keyed export which won't be cached.

I can fix the problem for version 6.4.1 but I won't be fast. I think caching will need to be a different issue and I'd want to release version 6.5.0 for it as it's a major feature.

**Comment by eglauko** [comment]
Let me ask something: The IMissingDependencyExpressionProvider is used when i call the locate method?

My wrapper implements also the IMissingDependencyExpressionProvider, and I'm configuring this way:

```
var container = new DependencyInjectionContainer(GraceDynamicMethod.Configuration());
container.Configure(c =>
{
    var optionalStrategy = new OptionalWrapperStrategy(c.OwningScope);
    c.AddActivationStrategy(optionalStrategy);
    c.AddMissingDependencyExpressionProvider(optionalStrategy);
});
```
I realized that the IMissingDependencyExpressionProvider methods were not called from locate. Maybe using this strategy would solve the problem.

**Comment by ipjohnson** [comment]
@eglauko you are correct the `IMissingDependencyExpressionProvider` methods weren't being called because you were registering it as a strategy all that said I think you've stumbled on a bug that is going to be hard to fix without making a change to the `IWrapperOrExportActivationStrategy` interface.

After doing some digging the problem is going to affect all Wrapped/Keyed Locate requests. Essentially the `GetActivationStrategyDelegate` method needs to have key added to it but this will be a breaking change that I don't want to introduce in the 6.X series.

Now to the bad news I don't think I'm going to be able to start Grace 7 till next year because of a number of different family and work related obligations. This will most definitely make the list as well as caching keyed delegates but I just can't start the work now.

**Comment by ipjohnson** [comment]
@eglauko I think this solution will work for the moment and for 7 I'll remove the interface and add the object key parameter to `IWrapperOrExportActivationStrategy`

**Comment by eglauko** [comment]
Yes, I understood what you wanted to do and I created a solution to solve this problem without creating any impact on the current version.

I thought you could create another cache in the BaseExportLocatorScope class, similar to the ActivationDelegates cache, for delegates with type and key. And in the locate method of the InjectionScope class you could create and search for these keyed delegates.

**Comment by eglauko** [comment]
Could you release a preview version with this PR?

**Comment by ipjohnson** [comment]
I can do that this evening.

**Comment by ipjohnson** [comment]
I'm pushing out a release this evening for this. Glad it worked out
