### ISSUE TITLE
ExtraData isn't used

### ISSUE THREAD

**Issue by SuperJMN** [ipjohnson/Grace#236]
Given this test, I expect `myClass` to be instatiated, but it's not. It tried to create an instance of `DependencyA` instead of the provided one (via **ExtraData**).

```
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var c = new DependencyInjectionContainer();
            c.Configure(x => x.Export<MyClass>());
            c.Configure(x => x.Export<DependencyB>());

            var myClass = c.Locate<MyClass>(new { depA = new DependencyA("greetings")});
        }
    }

    public class MyClass
    {
        public MyClass(DependencyA depA, DependencyB depB)
        {
            
        }
    }

    public class DependencyB
    {
    }

    public class DependencyA
    {
        public DependencyA(string str)
        {
            
        }
    }
```

**Comment by ipjohnson** [comment]
@SuperJMN I'm leaving a comment just in case other people find this as we already discussed this offline.

The reason why the extra data is not used is because grace will attempt to concrete types first instead of looking in extra data. There are a couple ways to address this.

* Register a function that takes IInjectionContext as an arg and returns the dependency from the context. (best performance)

```
c.Configure(c => c.ExportFactory<IInjectionContext,DependencyA>(
     context => context.GetExtraData('depA')));
```

*  Turn off auto registration. `AutoRegisterUnknown = false` (probably not good for asp.net apps)

* Use an interfaces instead of concrete type for parameter to constructor.

* Do something specific with the DependencyB registration where you specify where A comes from.
