### ISSUE TITLE
QUESTION: Does Grace support Azure Functions 3

### ISSUE THREAD

**Issue by shahabganji** [ipjohnson/Grace#271]
Dear @ipjohnson,

I am developing an azure function application and I want to use Grace within that application as the container. Is it possible? if so would you mind guide me through that or put a link in which I could follow the instructions? I know something about other containers like [this](https://github.com/junalmeida/autofac-azurefunctions#get-started-in-azure-functions) one, but I prefer to go with Grace.

Does it also supports [this](https://stackoverflow.com/questions/64817394/mediatr-ipipelinebehavior-conversion-failed-at-runtime) scenario?

**Comment by silkfire** [comment]
I think it probably works the same as in ASP.NET, except you just add the special attribute at the top of your file:

`[assembly: FunctionsStartup(typeof(Startup))]`

**Comment by ipjohnson** [comment]
@shahabganji  I believe @silkfire  is correct. Reading this [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) it sounds like it's supported out of the box with nothing special required from any 3rd party DI container.

Have you tried using it? I'm not familiar with azure functions so I'm a little in the dark in how they work.

**Comment by shahabganji** [comment]
@silkfire @ipjohnson I am aware of that, and it seems they are using the DryIoc behind the scenes and it supports my scenario actually. Thanks for your time and response guys 🙏

**Comment by ipjohnson** [comment]
@shahabganji I'm confused what specifically is not being supported?

**Comment by shahabganji** [comment]
@ipjohnson 

In [this sample](https://github.com/jbogard/MediatR/issues/583) when I use only `ServiceCollection` and try to use that it throws an error at runtime and based on [this answer](https://stackoverflow.com/questions/64817394/mediatr-ipipelinebehavior-conversion-failed-at-runtime?noredirect=1#comment114600732_64817394) by Steven @dotnetjunkie, it seems to be a problem for MS.DI.

https://github.com/jbogard/MediatR/wiki/Container-Feature-Support
https://github.com/jbogard/MediatR/issues/305#issuecomment-417002645

**Comment by ipjohnson** [comment]
@shahabganji gotcha, yes steven is correct it's a feature that is not supported in MS.DI. I was confused and thought there was an issue with Grace which I would want to try and address.

Thanks for the clarification

**Comment by shahabganji** [comment]
@ipjohnson Actually, I am not sure how to replace the built-in version in azure functions with Grace, I recall in ASP.NET Core we used `UseGrace` on host builder and then adding `ConfigureContainer` on the `Startup` class, and Grace will take place instead of the built-in DI, but in Azure Functions, I did not see those capabilities, if you happen to find a way, please ping me 🙏

**Comment by ipjohnson** [comment]
Looks like all the magic happen [here](https://github.com/junalmeida/autofac-azurefunctions/blob/master/Autofac.Extensions.DependencyInjection.AzureFunctions/ConfigurationExtensions.cs). I can't address it at this moment but I'll try and find 30 minutes this weekend to write up what it would look like if you used Grace instead of Autofac.

**Comment by shahabganji** [comment]
@ipjohnson yes, that is exactly the place where Autofac uses

**Comment by ipjohnson** [comment]
So I spent some time looking at the autofac solution and it's not quite as straight forward as I originally anticipated. It looks like there is no MS sanctioned way of replacing the DI container.

It looks like you end up running two DI containers in the app vs. asp.net core where you have just one service provider. You also end up replacing some of the classes with DI specific implementations which may or may not age well. 

I'm hesitant to publish a nuget package with something like this because I don't work with azure functions. That said I'd be willing to put out a repo with the code that you could copy into your project (3-4 files). Would that work?

**Comment by shahabganji** [comment]
@ipjohnson Thanks for the time and support 🙏🏼 , from the perspective that you described I think it is rational not to publish a NuGet package. 

A repo would be awesome actually; at least I'll try it and will update you with the feedback, and maybe in the future releases they make it a bit third-party friendly.

Thank you anyway 👍🏼
