### ISSUE TITLE
Asp.Net vNext Support

### ISSUE THREAD

**Issue by prasannavl** [ipjohnson/Grace#28]
Support for Asp.Net vNext? 

Has to do automatic re-population from `IServiceCollection`, and then require both a new `ScopeProvider` and `IServiceProvider` implementation.

**Comment by ipjohnson** [comment]
Hi prasanna,

I played with vNext a while back and did create a nuget package for it here. https://github.com/ipjohnson/DependencyInjection

Once the final release comes out later this month I'll see about doing a finalized release. 

That being said I'm in the middle of buying a house so I won't have much time for the next month. 

Are you looking to start a project soon?

-Ian

**Comment by prasannavl** [comment]
This looks good. I can work with that. Shall contribute back, should I run into any problems, or unfinished issues.


Thanks!


Sent by Outlook for Android





On Wed, Jul 15, 2015 at 8:36 AM -0700, "Ian Johnson" <notifications@github.com> wrote:
Hi prasanna,

I played with vNext a while back and did create a nuget package for it here. https://github.com/ipjohnson/DependencyInjection

Once the final release comes out later this month I'll see about doing a finalized release.

That being said I'm in the middle of buying a house so I won't have much time for the next month.

Are you looking to start a project soon?

-Ian

---

**Comment by ipjohnson** [comment]
My hope was that at some point they would be putting out a nuget package with everything in it so all that would need to be done is reference the correct package rather than having to have the code in a clone of their repository. I don't know if they ever got around to it. 

It probably has a couple issues as it's almost a year out of date, that being said I don't think they changed it that much.

Contributions would be much appreciated.

**Comment by ipjohnson** [comment]
This has been released as a separate package located at https://github.com/ipjohnson/Grace.DependencyInjection.Extensions
